include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - admin_app/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    unnecessary_underscores: false
    unnecessary_brace_in_string_interps: false
    unused_field: ignore
    unused_element: ignore
    prefer_interpolation_to_compose_strings: ignore
