enum LearningLevel { foundation, intermediate, advanced, competitive }
enum LearningSection { numberSense, arithmetic, algebra, geometry, dataAndProbability, advancedMentalMath }

class LessonTopic {
  const LessonTopic({required this.id, required this.title, required this.section, required this.level, required this.summary, this.concepts = const [], this.methods = const [], this.examples = const [], this.traps = const [], this.practice = const []});
  final String id, title, summary;
  final LearningSection section;
  final LearningLevel level;
  final List<String> concepts, methods, examples, traps, practice;
  Map<String,dynamic> toMap()=>{'id':id,'title':title,'section':section.name,'level':level.name,'summary':summary,'concepts':concepts,'methods':methods,'examples':examples,'traps':traps,'practice':practice};
  factory LessonTopic.fromMap(Map<String,dynamic> m)=>LessonTopic(id:m['id']??'',title:m['title']??'',section:LearningSection.values.firstWhere((e)=>e.name==m['section'],orElse:()=>LearningSection.numberSense),level:LearningLevel.values.firstWhere((e)=>e.name==m['level'],orElse:()=>LearningLevel.foundation),summary:m['summary']??'',concepts:_s(m['concepts']),methods:_s(m['methods']),examples:_s(m['examples']),traps:_s(m['traps']),practice:_s(m['practice']));
  static List<String> _s(dynamic v)=>v is List?v.map((e)=>'$e').toList():const[];
}

class CurriculumCatalog {
  static const _foundation=['number-system','place-value','factors-multiples','divisibility','approximation','fractions-decimals','percentages','ratio-proportion','averages','algebra-basics','linear-equations','geometry-basics','bodmas'];
  static const _intermediate=['remainders','profit-loss-discount','simple-compound-interest','partnership','ages','time-work','pipes-cisterns','speed-distance','trains','arithmetic-progressions','statistics','mensuration-2d','pythagorean','mental-multiplication','fast-division','number-series'];
  static const _advanced=['mixture-alligation','boats-streams','geometric-progressions','quadratic-equations','indices-exponents','polynomials','sequences-patterns','mensuration-3d','trigonometry','permutation-combination','probability','data-interpretation','unit-digit','linear-speed-patterns'];

  static const List<LessonTopic> topics=[
    LessonTopic(id:'number-system',title:'Number System',section:LearningSection.numberSense,level:LearningLevel.foundation,summary:'Natural, whole, integer, rational, irrational and real-number reasoning; signs, parity, number line and representations.',concepts:['classification','sign and absolute value','parity','rational vs irrational'],methods:['classify before calculating','compare signed values by position','use parity to eliminate cases'],examples:['0 is whole but not positive','0.125=1/8','0.333…=1/3'],traps:['calling 0 positive','confusing recurring with irrational'],practice:['classification','ordering','parity','conversion']),
    LessonTopic(id:'place-value',title:'Place Value & Representation',section:LearningSection.numberSense,level:LearningLevel.foundation,summary:'Expanded form, powers of ten, rounding, scientific notation and digit manipulation.',concepts:['place value','powers of ten','rounding','scientific notation'],methods:['decompose into powers of 10','estimate before exact work'],examples:['48,305=40,000+8,000+300+5','4.83×10⁴'],traps:['dropping zero placeholders'],practice:['decomposition','rounding','estimation']),
    LessonTopic(id:'factors-multiples',title:'Factors, Multiples, HCF & LCM',section:LearningSection.numberSense,level:LearningLevel.foundation,summary:'Prime factorization, GCD/HCF, LCM and common multiples for fast divisibility and fraction work.',concepts:['prime factors','HCF','LCM'],methods:['factor once and reuse exponents','HCF×LCM=product for two positive integers'],examples:['12=2²×3;18=2×3² ⇒ HCF 6, LCM 36'],traps:['max exponents for HCF'],practice:['factorization','HCF','LCM']),
    LessonTopic(id:'divisibility',title:'Divisibility Rules',section:LearningSection.numberSense,level:LearningLevel.foundation,summary:'Fast tests for 2,3,4,5,6,8,9,10,11 and composite divisibility.',concepts:['digit sum','last digits','alternating sum'],methods:['apply cheapest rule first','combine 2 and 3 for 6','use last 2/3 digits for 4/8'],examples:['7,452 divisible by 4 because 52 is'],traps:['testing only last digit for 3/9'],practice:['missing digit','rule selection']),
    LessonTopic(id:'remainders',title:'Remainders & Modular Arithmetic',section:LearningSection.numberSense,level:LearningLevel.intermediate,summary:'Reduce large expressions modulo a divisor and exploit repeating cycles.',concepts:['quotient-remainder','modulo','congruence','cycles'],methods:['reduce factors first','track power cycles'],examples:['17 mod 5=2','2ⁿ mod 7 repeats every 3 powers'],traps:['remainder ≥ divisor'],practice:['remainders','power cycles']),
    LessonTopic(id:'approximation',title:'Approximation & Estimation',section:LearningSection.numberSense,level:LearningLevel.foundation,summary:'Mental estimation, bounds, compatible numbers and order-of-magnitude checks.',concepts:['rounding','bounds','sanity checks'],methods:['round strategically','estimate before exact calculation'],examples:['49×21≈50×20=1000'],traps:['over-rounding'],practice:['estimation','bounds']),
    LessonTopic(id:'averages',title:'Averages & Weighted Averages',section:LearningSection.arithmetic,level:LearningLevel.foundation,summary:'Mean, weighted mean, combined average and replacement problems using total-sum reasoning.',concepts:['mean=sum/count','weighted mean','combined groups','replacement effect'],methods:['think total first','change in total = change in average × count','use Σwx/Σw'],examples:['8 values average 15 ⇒ total 120'],traps:['averaging averages without weights'],practice:['mean','weighted mean','replacement','combined average']),
    LessonTopic(id:'ratio-proportion',title:'Ratio, Proportion & Variation',section:LearningSection.arithmetic,level:LearningLevel.foundation,summary:'Equivalent ratios, direct variation, inverse variation and proportional reasoning.',concepts:['scale factor','cross multiplication','direct/inverse variation'],methods:['a:b=ak:bk','identify constant product or ratio'],examples:['3:5 of 64 ⇒ 24:40'],traps:['adding ratio terms'],practice:['ratio division','proportion','variation']),
    LessonTopic(id:'percentages',title:'Percentages & Percentage Change',section:LearningSection.arithmetic,level:LearningLevel.foundation,summary:'Mental percentage calculation, reverse percentage and successive changes.',concepts:['percent of base','percentage points','successive factors'],methods:['use 1%','multiply factors for successive changes'],examples:['20% of 250=50','+20% then −20%=96%'],traps:['assuming +x and −x cancel'],practice:['mental percent','reverse percent','successive change']),
    LessonTopic(id:'profit-loss-discount',title:'Profit, Loss & Discount',section:LearningSection.arithmetic,level:LearningLevel.intermediate,summary:'CP, SP, MP, profit/loss margins and successive discounts.',concepts:['CP/SP/MP','profit on CP','discount on MP'],methods:['set CP=100','use multiplicative factors'],examples:['20% profit ⇒ SP=1.2CP','20% then 10% discount ⇒ 28%'],traps:['profit percentage on SP'],practice:['reverse price','discount chains']),
    LessonTopic(id:'simple-compound-interest',title:'Simple & Compound Interest',section:LearningSection.arithmetic,level:LearningLevel.intermediate,summary:'Linear SI versus multiplicative CI, amount, rate and compounding frequency.',concepts:['P,R,T','amount','annual/half-yearly/quarterly compounding'],methods:['SI=PRT/100','A=P(1+r/100)^n'],examples:['10% CI for 2 years ⇒ factor 1.21'],traps:['mixing rate and period units'],practice:['SI','CI','difference','amount']),
    LessonTopic(id:'mixture-alligation',title:'Mixture & Alligation',section:LearningSection.arithmetic,level:LearningLevel.advanced,summary:'Weighted concentration, price mixtures, alligation and replacement.',concepts:['weighted mean','cross difference','replacement'],methods:['place desired mean between values','use cross-differences'],examples:['20% and 50% to make 30% ⇒ 2:1'],traps:['reversing alligation'],practice:['concentration','price','replacement']),
    LessonTopic(id:'partnership',title:'Partnership',section:LearningSection.arithmetic,level:LearningLevel.intermediate,summary:'Share profit by capital × time.',concepts:['investment','capital-months','profit ratio'],methods:['multiply capital by duration'],examples:['100×12 equals 150×8'],traps:['using capital alone'],practice:['profit share']),
    LessonTopic(id:'ages',title:'Ages',section:LearningSection.arithmetic,level:LearningLevel.intermediate,summary:'Translate age statements into equations while keeping age differences invariant.',concepts:['present/past/future','age difference','age ratio'],methods:['define present ages','shift both ages equally'],examples:['A−B remains constant'],traps:['changing age difference'],practice:['age equations','ratios']),
    LessonTopic(id:'time-work',title:'Time, Work & Efficiency',section:LearningSection.arithmetic,level:LearningLevel.intermediate,summary:'Unit-work rates, combined work, efficiency and alternate work.',concepts:['rate=1/time','combined rate','efficiency'],methods:['take total work as LCM','add rates'],examples:['A in 6 days ⇒ rate 1/6'],traps:['adding completion times'],practice:['combined work','efficiency']),
    LessonTopic(id:'pipes-cisterns',title:'Pipes & Cisterns',section:LearningSection.arithmetic,level:LearningLevel.intermediate,summary:'Filling and draining as positive and negative rates.',concepts:['inlet','outlet','net rate'],methods:['fill rates add','leak rate subtract'],examples:['4h fill and 12h drain ⇒ net 1/6 tank/h'],traps:['adding leak'],practice:['net rate','multiple pipes']),
    LessonTopic(id:'speed-distance',title:'Speed, Distance & Time',section:LearningSection.arithmetic,level:LearningLevel.intermediate,summary:'D=ST, unit conversion, relative speed and average speed.',concepts:['D=ST','5/18 conversion','relative speed'],methods:['total distance/total time for average speed','relative speed for meetings'],examples:['equal-distance average speed=2ab/(a+b)'],traps:['averaging speeds directly'],practice:['conversion','relative speed','average speed']),
    LessonTopic(id:'trains',title:'Trains',section:LearningSection.arithmetic,level:LearningLevel.advanced,summary:'Train-platform and train-train crossing using combined lengths and relative speed.',concepts:['train length','platform length','relative speed'],methods:['distance=combined length'],examples:['two trains use sum of lengths'],traps:['forgetting relative speed'],practice:['crossing','platform']),
    LessonTopic(id:'boats-streams',title:'Boats & Streams',section:LearningSection.arithmetic,level:LearningLevel.advanced,summary:'Separate still-water speed and stream speed for upstream/downstream travel.',concepts:['downstream=boat+stream','upstream=boat−stream'],methods:['add/subtract equations'],examples:['15 downstream, 9 upstream ⇒ 12 still, 3 stream'],traps:['swapping directions'],practice:['upstream','downstream']),
    LessonTopic(id:'number-series',title:'Number Series & Pattern Recognition',section:LearningSection.numberSense,level:LearningLevel.intermediate,summary:'Arithmetic, geometric, alternating, difference-of-differences, polynomial and position-based patterns.',concepts:['first/second differences','ratios','odd/even interleaving','position formulas'],methods:['write difference rows','split odd/even terms','check squares/cubes/primes'],examples:['2,5,10,17 ⇒ +3,+5,+7 ⇒ 26','1,4,9,16 ⇒ n²'],traps:['forcing one rule'],practice:['differences','ratios','alternating','polynomial']),
    LessonTopic(id:'arithmetic-progressions',title:'Arithmetic Progressions',section:LearningSection.algebra,level:LearningLevel.intermediate,summary:'Constant-difference sequences, nth term and finite sums.',concepts:['a,d,nth term','sum'],methods:['aₙ=a+(n−1)d','S=n/2[2a+(n−1)d]'],examples:['3,7,11 ⇒ d=4'],traps:['using nd'],practice:['nth term','sum']),
    LessonTopic(id:'geometric-progressions',title:'Geometric Progressions',section:LearningSection.algebra,level:LearningLevel.advanced,summary:'Constant-ratio sequences, finite sums and growth/decay.',concepts:['a,r,nth term','geometric sum'],methods:['aₙ=ar^(n−1)'],examples:['2,6,18,54 ⇒ r=3'],traps:['using AP formulas'],practice:['ratio','nth term','sum']),
    LessonTopic(id:'algebra-basics',title:'Algebraic Identities & Factorisation',section:LearningSection.algebra,level:LearningLevel.foundation,summary:'Like terms, identities, expansion, substitution and factorisation.',concepts:['(a+b)²','(a−b)²','a²−b²'],methods:['recognize identities before expanding','factor common terms'],examples:['(a+b)²=a²+2ab+b²'],traps:['sign errors'],practice:['identities','factorization']),
    LessonTopic(id:'linear-equations',title:'Linear Equations',section:LearningSection.algebra,level:LearningLevel.foundation,summary:'Solve one-variable equations and translate word conditions.',concepts:['balance','coefficients','unknowns'],methods:['collect terms','verify by substitution'],examples:['3x+5=20 ⇒ x=5'],traps:['unbalanced sign changes'],practice:['solve x','word equations']),
    LessonTopic(id:'quadratic-equations',title:'Quadratic Equations',section:LearningSection.algebra,level:LearningLevel.advanced,summary:'Factorisation, quadratic formula, discriminant and root relationships.',concepts:['roots','discriminant','Vieta'],methods:['factor first','use formula when needed','use sum/product for speed'],examples:['x²−5x+6=0 ⇒ 2,3'],traps:['forgetting ±'],practice:['roots','discriminant']),
    LessonTopic(id:'indices-exponents',title:'Indices, Exponents & Surds',section:LearningSection.algebra,level:LearningLevel.advanced,summary:'Exponent laws, negative/fractional indices and surd manipulation.',concepts:['power laws','fractional powers','surds'],methods:['convert roots to powers','rationalize simple denominators'],examples:['a^m a^n=a^(m+n)','√a=a^(1/2)'],traps:['adding exponents across addition'],practice:['laws','surds']),
    LessonTopic(id:'polynomials',title:'Polynomials & Factor Theorem',section:LearningSection.algebra,level:LearningLevel.advanced,summary:'Roots, factor theorem, remainder theorem and structured factorisation.',concepts:['degree','roots','factor/remainder theorem'],methods:['test small roots','group terms'],examples:['p(2)=0 ⇒ x−2 is a factor'],traps:['wrong root sign'],practice:['factors','remainders']),
    LessonTopic(id:'sequences-patterns',title:'Advanced Sequence Patterns',section:LearningSection.algebra,level:LearningLevel.advanced,summary:'Alternating, recursive, interleaved and position-dependent sequences.',concepts:['odd/even split','recursive rules','polynomial patterns'],methods:['split positions','compare difference layers','test n-formulas'],examples:['1,3,7,15 ⇒ ×2+1','2,6,12,20 ⇒ n(n+1)'],traps:['assuming AP/GP only'],practice:['alternating','recursive','n-th term']),
    LessonTopic(id:'geometry-basics',title:'Geometry Foundations',section:LearningSection.geometry,level:LearningLevel.foundation,summary:'Angles, triangles, polygons, coordinates and basic geometric reasoning.',concepts:['angle sums','triangle properties','polygon sums','distance/midpoint'],methods:['draw auxiliary lines','use known sums first'],examples:['triangle=180°','n-gon=(n−2)180°'],traps:['interior/exterior confusion'],practice:['angles','triangles','polygons']),
    LessonTopic(id:'mensuration-2d',title:'Mensuration 2D',section:LearningSection.geometry,level:LearningLevel.intermediate,summary:'Perimeter, area and composite figures.',concepts:['rectangle','triangle','circle','trapezium','rhombus'],methods:['split composite shapes','track squared units'],examples:['circle area=πr²'],traps:['diameter as radius'],practice:['area','perimeter']),
    LessonTopic(id:'mensuration-3d',title:'Mensuration 3D',section:LearningSection.geometry,level:LearningLevel.intermediate,summary:'Volume, curved surface area and total surface area.',concepts:['cube/cuboid','cylinder','cone','sphere'],methods:['choose requested measure','check dimensions'],examples:['cylinder=πr²h','cone=⅓πr²h'],traps:['CSA vs TSA'],practice:['volume','surface area']),
    LessonTopic(id:'pythagorean',title:'Pythagorean Theorem & Triplets',section:LearningSection.geometry,level:LearningLevel.intermediate,summary:'Right triangles and common triples for fast mental geometry.',concepts:['a²+b²=c²','3-4-5','5-12-13','8-15-17'],methods:['memorize base triples','scale them'],examples:['6-8-10'],traps:['wrong hypotenuse'],practice:['missing side','triplets']),
    LessonTopic(id:'trigonometry',title:'Trigonometry',section:LearningSection.geometry,level:LearningLevel.advanced,summary:'Standard-angle values, identities and right-triangle ratios.',concepts:['sin/cos/tan','reciprocal ratios','sin²+cos²=1'],methods:['memorize standard table','reduce identities first'],examples:['sin30=.5','tan45=1'],traps:['swapping sin/cos'],practice:['standard values','identities']),
    LessonTopic(id:'permutation-combination',title:'Permutations & Combinations',section:LearningSection.dataAndProbability,level:LearningLevel.advanced,summary:'Count ordered arrangements and unordered selections efficiently.',concepts:['factorial','nPr','nCr'],methods:['decide if order matters','cancel factorials early'],examples:['5P2=20;5C2=10'],traps:['using nPr for selection'],practice:['arrangements','selections']),
    LessonTopic(id:'probability',title:'Probability',section:LearningSection.dataAndProbability,level:LearningLevel.advanced,summary:'Sample spaces, complements, independent and conditional events.',concepts:['favourable/total','complement','independence'],methods:['count complement when easier','use trees for stages'],examples:['P(not A)=1−P(A)'],traps:['adding independent probabilities'],practice:['counting','complements']),
    LessonTopic(id:'data-interpretation',title:'Data Interpretation',section:LearningSection.dataAndProbability,level:LearningLevel.advanced,summary:'Tables, ratios, percentages, averages and missing-data reasoning.',concepts:['totals','ratios','percentage change','averages'],methods:['estimate first','cross-check row/column totals'],examples:['120 of 500=24%'],traps:['wrong row/column'],practice:['tables','percentages','averages']),
    LessonTopic(id:'statistics',title:'Statistics',section:LearningSection.dataAndProbability,level:LearningLevel.intermediate,summary:'Mean, median, mode, range and effects of shifts/outliers.',concepts:['mean','median','mode','range'],methods:['sort before median','total/count for mean'],examples:['add 5 to all values ⇒ mean+5'],traps:['median without sorting'],practice:['summary measures']),
    LessonTopic(id:'mental-multiplication',title:'Fast Multiplication Techniques',section:LearningSection.advancedMentalMath,level:LearningLevel.intermediate,summary:'Distributive, near-base and identity-based multiplication shortcuts.',concepts:['×5/25/50','near 100','difference of squares'],methods:['×25=×100÷4','99×101=100²−1'],examples:['48×25=1200'],traps:['zero placement'],practice:['two-digit products','near-base']),
    LessonTopic(id:'fast-division',title:'Fast Division',section:LearningSection.advancedMentalMath,level:LearningLevel.intermediate,summary:'Factor cancellation, scaling and familiar fraction conversion for fast division.',concepts:['cancellation','scaling','reciprocals'],methods:['÷25=×4÷100','simplify factors before decimals'],examples:['750÷25=30'],traps:['cancelling across addition'],practice:['division shortcuts']),
    LessonTopic(id:'unit-digit',title:'Unit Digit & Last-Digit Cycles',section:LearningSection.numberSense,level:LearningLevel.advanced,summary:'Cyclic last digits of powers and products.',concepts:['mod 10 cycles','cycle length'],methods:['write cycle','reduce exponent modulo cycle length'],examples:['2 powers cycle 2,4,8,6'],traps:['remainder 0 handling'],practice:['large powers','products']),
    LessonTopic(id:'bodmas',title:'BODMAS & Simplification',section:LearningSection.arithmetic,level:LearningLevel.foundation,summary:'Deterministic order of operations for mixed expressions.',concepts:['brackets','orders','division/multiplication','addition/subtraction'],methods:['layer expression','left-to-right within same level'],examples:['2+3×4=14'],traps:['blind left-to-right'],practice:['mixed operations','nested brackets']),
    LessonTopic(id:'fractions-decimals',title:'Fractions & Decimals',section:LearningSection.arithmetic,level:LearningLevel.foundation,summary:'Exact conversion, comparison and operations with fractions and decimals.',concepts:['equivalent fractions','recurring decimals','common denominator'],methods:['reduce first','convert familiar fractions mentally'],examples:['3/8=.375'],traps:['adding denominators'],practice:['conversion','operations']),
    LessonTopic(id:'linear-speed-patterns',title:'Advanced Word-Problem Translation',section:LearningSection.arithmetic,level:LearningLevel.advanced,summary:'Turn dense verbal conditions into equations, rates and constraints before solving.',concepts:['variables','constraints','units'],methods:['define unknowns','write one equation per condition','verify dimensions'],examples:['distance/time statements become D=ST'],traps:['calculating before modeling'],practice:['translation','equation setup']),
  ];
  static LessonTopic? byId(String id)=>topics.cast<LessonTopic?>().firstWhere((t)=>t!.id==id,orElse:()=>null);
  static List<LessonTopic> search(String query){final q=query.toLowerCase().trim();if(q.isEmpty)return topics;return topics.where((t)=>t.title.toLowerCase().contains(q)||t.summary.toLowerCase().contains(q)).toList();}
}
