import 'package:flutter/material.dart';
import 'package:speed_math_content/curriculum.dart';
import '../../app/theme/app_colors.dart';
import 'topic_learn_screen.dart';

class LearnScreen extends StatefulWidget { const LearnScreen({super.key}); @override State<LearnScreen> createState()=>_LearnScreenState(); }
class _LearnScreenState extends State<LearnScreen> {
 String q=''; LearningSection? section;
 @override Widget build(BuildContext context){ final dark=Theme.of(context).brightness==Brightness.dark; final list=CurriculumCatalog.topics.where((t)=>(section==null||t.section==section)&&(q.isEmpty||t.title.toLowerCase().contains(q.toLowerCase())||t.summary.toLowerCase().contains(q.toLowerCase()))).toList(); return Scaffold(backgroundColor:dark?AppColors.backgroundDark:const Color(0xFFF5F7FB),appBar:AppBar(title:const Text('Learn',style:TextStyle(fontWeight:FontWeight.w900)),backgroundColor:Colors.transparent),body:ListView(padding:const EdgeInsets.fromLTRB(16,8,16,110),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:AppColors.primary.withValues(alpha:.08),borderRadius:BorderRadius.circular(22)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Learn the idea first.',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),SizedBox(height:6),Text('Concept → method → example → common trap → Practice.',style:TextStyle(height:1.35))]),const SizedBox(height:14),TextField(decoration:InputDecoration(prefixIcon:const Icon(Icons.search_rounded),hintText:'Search topics…',filled:true,fillColor:dark?AppColors.cardDark:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide.none)),onChanged:(v)=>setState(()=>q=v)),const SizedBox(height:10),Wrap(spacing:7,children:[ChoiceChip(label:const Text('All'),selected:section==null,onSelected:(_)=>setState(()=>section=null)),...LearningSection.values.map((s)=>ChoiceChip(label:Text(_label(s)),selected:section==s,onSelected:(_)=>setState(()=>section=s)))]),const SizedBox(height:14),Text('${list.length} topics',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:16)),const SizedBox(height:8),...list.map((t)=>Card(elevation:0,margin:const EdgeInsets.only(bottom:8),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18)),child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:14,vertical:6),leading:CircleAvatar(backgroundColor:AppColors.primary.withValues(alpha:.1),child:const Icon(Icons.auto_stories_rounded,color:AppColors.primary)),title:Text(t.title,style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text(t.summary,maxLines:2,overflow:TextOverflow.ellipsis),trailing:const Icon(Icons.chevron_right_rounded),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>TopicLearnScreen(topic:t)))))]); }
 String _label(LearningSection s)=>switch(s){LearningSection.numberSense=>'Number Sense',LearningSection.arithmetic=>'Arithmetic',LearningSection.algebra=>'Algebra',LearningSection.geometry=>'Geometry',LearningSection.dataAndProbability=>'Data',LearningSection.advancedMentalMath=>'Mental Math'};
}
